// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmleGAjFYpyVxyTUoR9freReKxKvzF9iI',
    appId: '1:1015364231733:web:ecdb30e84253b505f5077c',
    messagingSenderId: '1015364231733',
    projectId: 'mybudget-tracker-app',
    authDomain: 'mybudget-tracker-app.firebaseapp.com',
    storageBucket: 'mybudget-tracker-app.firebasestorage.app',
    measurementId: 'G-L5DBR7VEXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZHHqpLqkuSySPgMc8Y9I0-P2K8WuQS1U',
    appId: '1:1015364231733:android:529e27383c9b0696f5077c',
    messagingSenderId: '1015364231733',
    projectId: 'mybudget-tracker-app',
    storageBucket: 'mybudget-tracker-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4uJ50Aol-8mMKg0u8fCfTEC-zaPFk2FI',
    appId: '1:1015364231733:ios:097f87e3a9abef08f5077c',
    messagingSenderId: '1015364231733',
    projectId: 'mybudget-tracker-app',
    storageBucket: 'mybudget-tracker-app.firebasestorage.app',
    iosBundleId: 'com.example.myproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4uJ50Aol-8mMKg0u8fCfTEC-zaPFk2FI',
    appId: '1:1015364231733:ios:097f87e3a9abef08f5077c',
    messagingSenderId: '1015364231733',
    projectId: 'mybudget-tracker-app',
    storageBucket: 'mybudget-tracker-app.firebasestorage.app',
    iosBundleId: 'com.example.myproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmleGAjFYpyVxyTUoR9freReKxKvzF9iI',
    appId: '1:1015364231733:web:e375d2447c3b28f3f5077c',
    messagingSenderId: '1015364231733',
    projectId: 'mybudget-tracker-app',
    authDomain: 'mybudget-tracker-app.firebaseapp.com',
    storageBucket: 'mybudget-tracker-app.firebasestorage.app',
    measurementId: 'G-BGRM89XFQ7',
  );
}
